#!/usr/bin/env bash

export ALIAS_COMMANDS_FILE="$HOME/aliascli/alias_commands"
export ALIAS_CLI_FILE="$HOME/aliascli/alias_cli"
source "$ALIAS_COMMANDS_FILE"                                                                                          

function al() {
    if [[ $1 == "-h" ]]; then
        echo "al -h                : show this help page"
        echo "al -o                : opens the alias commands file"
        echo "al                   : list all aliases"
        echo "al <string>          : list aliases containing <string>"
        echo "al -d <string>       : delete aliases containing <string>"
        echo "al -v <string>       : view command for an alias"
        echo "al <alias> <command> : create a new alias or update an existing one"
        return 0
    fi

    if [[ $# -eq 0 ]]; then
        grep "^alias" "$ALIAS_COMMANDS_FILE" | sed 's/^alias //g'
    elif [[ $# -eq 1 ]]; then
        grep "$1" "$ALIAS_COMMANDS_FILE" | sed 's/^alias //g'
    elif [[ $1 == "-v" ]]; then
        ALIAS_COMMAND=$(grep "alias $2=" "$ALIAS_COMMANDS_FILE" | sed "s/alias $2='\(.*\)'$/\1/")
        if [[ -n $ALIAS_COMMAND ]]; then
            echo "$ALIAS_COMMAND"
        else
            echo "No command found for alias: $2"
        fi
    elif [[ $1 == "-o" ]]; then
        open "$ALIAS_CLI_FILE"
    elif [[ $1 =~ ^-[Dd]$ ]]; then
        if [[ $# -lt 2 ]]; then
            echo "Please specify an alias to delete"
            return 1
        fi
        DELETED_COMMAND=$(grep "alias $2=" "$ALIAS_COMMANDS_FILE" | sed "s/alias $2='\(.*\)'$/\1/")
        echo "Delete '$DELETED_COMMAND'? (y/N)"
        read
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            sed -i.bak "/^alias $2=.*/d" "$ALIAS_COMMANDS_FILE"
            echo "Deleted $2"
        fi
    elif [[ $# -eq 2 ]]; then
        if grep "^alias $1=" "$ALIAS_COMMANDS_FILE"; then
            EXISTING_COMMAND=$(grep "^alias $1=" "$ALIAS_COMMANDS_FILE" | sed "s/^alias $1='\(.*\)'$/\1/")
            echo "\"$1\" already exists"
            echo "Update to \"$2\"? (y/N) "
            read
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                sed -i.bak "/^alias $1=\"/d" "$ALIAS_COMMANDS_FILE"
                echo "alias $1=\"$2\"" >> "$ALIAS_COMMANDS_FILE"
                echo "Updated $1 -> \"$2\""
            fi
        else
            echo "alias $1=\"$2\"" >> "$ALIAS_COMMANDS_FILE"
        fi
    else
        echo "Invalid arguments"
        return 1
    fi

    source "$ALIAS_COMMANDS_FILE"
}
